export const carRentApiConst = {
    // LOGIN_API_URL :'https://aqueous-earth-02633-e729ae53b1b3.herokuapp.com/api/users/',
    BOOKING_API_URL : ' https://aqueous-earth-02633-e729ae53b1b3.herokuapp.com/api/bookings/',
    ADMIN_API_URL : 'https://aqueous-earth-02633-e729ae53b1b3.herokuapp.com/api/admin/',
    // USER_API_URL : ' https://aqueous-earth-02633-e729ae53b1b3.herokuapp.com/api/users/',
    // API_URL : 'https://aqueous-earth-02633-e729ae53b1b3.herokuapp.com/api/',
    API_URL : 'http://localhost:7254/api/',
    USER_REGIST : 'Auth/RegiterUser',
    USER_LOGIN : 'Auth/SignIN',
    OTP_VERYFI : 'Auth/OTPVarification',
    RESEND_VERYFI_OTP : 'Auth/resend-otp',
    FORGET_PASSWORD : 'Auth/forgot-password',
    RESETPASSWORD: 'Auth/reset-password',
    profile_creating:'UserProfile/uers_profile_creation',
    getting_profile: 'UserProfile',
    updated_user_profile :'UserProfile/UpdateUserProfile',
    FAVOURITE_CARS :'FavouriteCars/GetFavourites',
    ADD_TO_FAVOURITE : 'FavouriteCars/AddToFavourite',
    REMOVE_FROM_FAVOURITE : 'FavouriteCars/RemoveFromFavourites',
    // ADD_CARS : 'add',
    GET_ALL_CARS : 'Cars/get-all',
    GETTING_CAR_BY_Id :'Cars/GetById'
    // GET_USER_ID : 'get/1',
    // AVAILABLE_CARS : 'cars/available',
    // ADD_BOOKING : 'add?carId=3&startDate=2024-10-08 10:00&endDate=2024-10-10 10:00',
    // GET_BOOKING_CARS : 'all',
    // CANCEL_BOOKING : 'cancel/1',
    // LOGGED_USER_BOOKING : 'users/rentals',
    // UPDATE_DETAIL : 'update/6',
    // RESETPASOTP: 'auth/reset-pass-otp-verify'
}